from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy import BigInteger,String,Text,Integer,Boolean,DateTime,JSON,ForeignKey
from datetime import datetime
class Base(DeclarativeBase): pass
class User(Base):
    __tablename__='users'; id:Mapped[int]=mapped_column(primary_key=True); telegram_id:Mapped[int]=mapped_column(BigInteger,unique=True,index=True); username:Mapped[str|None]=mapped_column(String(255)); first_name:Mapped[str|None]=mapped_column(String(255)); language:Mapped[str]=mapped_column(String(2),default='uz'); registration_status:Mapped[bool]=mapped_column(Boolean,default=False); vip_expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); referred_by:Mapped[int|None]=mapped_column(BigInteger); referral_count:Mapped[int]=mapped_column(default=0); qualified_referral_count:Mapped[int]=mapped_column(default=0); is_blocked:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow); last_activity:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow)
class Movie(Base):
    __tablename__='movies'; id:Mapped[int]=mapped_column(primary_key=True); code:Mapped[str]=mapped_column(String(64),unique=True,index=True); title_uz:Mapped[str]=mapped_column(Text); title_ru:Mapped[str]=mapped_column(Text); description_uz:Mapped[str|None]=mapped_column(Text); description_ru:Mapped[str|None]=mapped_column(Text); description_uz_entities:Mapped[list|None]=mapped_column(JSON); description_ru_entities:Mapped[list|None]=mapped_column(JSON); year:Mapped[int|None]=mapped_column(); genre:Mapped[str|None]=mapped_column(String(255)); country:Mapped[str|None]=mapped_column(String(255)); rating:Mapped[str|None]=mapped_column(String(32)); poster_file_id:Mapped[str|None]=mapped_column(String(512)); video_file_id:Mapped[str|None]=mapped_column(String(512)); video_file_unique_id:Mapped[str|None]=mapped_column(String(512)); source_channel_id:Mapped[int|None]=mapped_column(BigInteger); source_message_id:Mapped[int|None]=mapped_column(BigInteger); vip_only:Mapped[bool]=mapped_column(Boolean,default=False); views:Mapped[int]=mapped_column(default=0); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow)
class Series(Base):
    __tablename__='series'; id:Mapped[int]=mapped_column(primary_key=True); code:Mapped[str]=mapped_column(String(64),unique=True,index=True); title_uz:Mapped[str]=mapped_column(Text); title_ru:Mapped[str]=mapped_column(Text); description_uz:Mapped[str|None]=mapped_column(Text); description_ru:Mapped[str|None]=mapped_column(Text); description_uz_entities:Mapped[list|None]=mapped_column(JSON); description_ru_entities:Mapped[list|None]=mapped_column(JSON); year:Mapped[int|None]=mapped_column(); genre:Mapped[str|None]=mapped_column(String(255)); country:Mapped[str|None]=mapped_column(String(255)); rating:Mapped[str|None]=mapped_column(String(32)); poster_file_id:Mapped[str|None]=mapped_column(String(512)); vip_only:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow)
class Episode(Base):
    __tablename__='episodes'; id:Mapped[int]=mapped_column(primary_key=True); series_id:Mapped[int]=mapped_column(ForeignKey('series.id',ondelete='CASCADE'),index=True); season_number:Mapped[int]; episode_number:Mapped[int]; title_uz:Mapped[str|None]=mapped_column(Text); title_ru:Mapped[str|None]=mapped_column(Text); description_uz:Mapped[str|None]=mapped_column(Text); description_ru:Mapped[str|None]=mapped_column(Text); description_uz_entities:Mapped[list|None]=mapped_column(JSON); description_ru_entities:Mapped[list|None]=mapped_column(JSON); video_file_id:Mapped[str|None]=mapped_column(String(512)); video_file_unique_id:Mapped[str|None]=mapped_column(String(512)); source_channel_id:Mapped[int|None]=mapped_column(BigInteger); source_message_id:Mapped[int|None]=mapped_column(BigInteger); vip_only:Mapped[bool]=mapped_column(Boolean,default=False); views:Mapped[int]=mapped_column(default=0); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow)
class MandatoryChannel(Base):
    __tablename__='mandatory_channels'; id:Mapped[int]=mapped_column(primary_key=True); chat_id:Mapped[int]=mapped_column(BigInteger,index=True); title:Mapped[str]=mapped_column(Text); url:Mapped[str]=mapped_column(Text); chat_type:Mapped[str]=mapped_column(String(32)); tracking_code:Mapped[str]=mapped_column(String(64),unique=True); active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow)
class SubscriptionTracking(Base):
    __tablename__='subscription_tracking'; id:Mapped[int]=mapped_column(primary_key=True); subscription_id:Mapped[int]=mapped_column(ForeignKey('mandatory_channels.id',ondelete='CASCADE')); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE')); tracking_code:Mapped[str|None]=mapped_column(String(64)); invite_link:Mapped[str|None]=mapped_column(Text); event_type:Mapped[str|None]=mapped_column(String(64)); joined_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); checked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); is_subscribed:Mapped[bool|None]=mapped_column(Boolean); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow)
class VipPlan(Base):
    __tablename__='vip_plans'; id:Mapped[int]=mapped_column(primary_key=True); name_uz:Mapped[str]; name_ru:Mapped[str]; days:Mapped[int]; price:Mapped[int]; active:Mapped[bool]=mapped_column(Boolean,default=True)
class VipPayment(Base):
    __tablename__='vip_payments'; id:Mapped[int]=mapped_column(primary_key=True); payment_id:Mapped[str]=mapped_column(String(64),unique=True,index=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); plan_id:Mapped[int]=mapped_column(ForeignKey('vip_plans.id')); amount:Mapped[int]; currency:Mapped[str]=mapped_column(String(8),default='UZS'); status:Mapped[str]=mapped_column(String(16),default='PENDING'); receipt_file_id:Mapped[str|None]=mapped_column(String(512)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow); verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); verified_by:Mapped[int|None]=mapped_column(BigInteger); rejection_reason:Mapped[str|None]=mapped_column(Text)
class VipTransaction(Base):
    __tablename__='vip_transactions'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); type:Mapped[str]; days:Mapped[int]; payment_id:Mapped[str|None]=mapped_column(String(64)); admin_id:Mapped[int|None]=mapped_column(BigInteger); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow)
class Referral(Base):
    __tablename__='referrals'; id:Mapped[int]=mapped_column(primary_key=True); referrer_id:Mapped[int]=mapped_column(ForeignKey('users.id')); referred_user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),unique=True); status:Mapped[str]=mapped_column(String(32),default='PENDING'); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow); qualified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class ReferralReward(Base):
    __tablename__='referral_rewards'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); required_referrals:Mapped[int]; from_referral_number:Mapped[int]; to_referral_number:Mapped[int]; vip_days:Mapped[int]; created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow)
class Setting(Base):
    __tablename__='settings'; key:Mapped[str]=mapped_column(String(100),primary_key=True); value:Mapped[str|None]=mapped_column(Text)
class Broadcast(Base):
    __tablename__='broadcasts'; id:Mapped[int]=mapped_column(primary_key=True); admin_id:Mapped[int]; kind:Mapped[str]; sent:Mapped[int]=mapped_column(default=0); failed:Mapped[int]=mapped_column(default=0); blocked:Mapped[int]=mapped_column(default=0); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow)
class ContentView(Base):
    __tablename__='content_views'; id:Mapped[int]=mapped_column(primary_key=True); content_type:Mapped[str]; content_id:Mapped[int]; user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=datetime.utcnow)
