from aiogram import Router,F
from aiogram.filters import CommandStart
from aiogram.types import Message,CallbackQuery
from aiogram.fsm.context import FSMContext
from sqlalchemy import select
from datetime import datetime,timezone
from app.database.database import Session
from app.database.models import User,Movie,Series
from app.keyboards.user import lang,main,phone
from app.handlers.subscriptions import show
from app.locales.uz import TEXT as UZ
from app.locales.ru import TEXT as RU
from app.config import settings
from app.utils.protection import protect_for_user
from app.utils.entities import deserialize_entities
from aiogram.types import InlineKeyboardMarkup,InlineKeyboardButton
router=Router()
def vip(u):return bool(u.vip_expires_at and u.vip_expires_at>datetime.now(timezone.utc))
@router.message(CommandStart())
async def start(m,state):
 await state.clear();payload=m.text.split(' ',1)[1].strip() if m.text and ' ' in m.text else ''
 async with Session() as s:
  u=(await s.execute(select(User).where(User.telegram_id==m.from_user.id))).scalar_one_or_none()
  if not u:u=User(telegram_id=m.from_user.id,username=m.from_user.username,first_name=m.from_user.first_name);s.add(u);await s.commit()
 await state.update_data(start_payload=payload);await m.answer('Tilni tanlang / Выберите язык:',reply_markup=lang())
@router.callback_query(F.data.startswith('lang_'))
async def language(c,state):
 lng=c.data.split('_')[1]
 async with Session() as s:u=(await s.execute(select(User).where(User.telegram_id==c.from_user.id))).scalar_one();u.language=lng;await s.commit()
 await c.message.answer((UZ if lng=='uz' else RU)['welcome'],reply_markup=phone());await c.answer()
async def open_payload(m,payload):
 if not payload:return
 kind,_,code=payload.partition('_')
 async with Session() as s:
  u=(await s.execute(select(User).where(User.telegram_id==m.from_user.id))).scalar_one_or_none()
  if not u:return
  if not vip(u) and not await __import__('app.services.subscription_service',fromlist=['check_all']).check_all(m.bot,m.from_user.id,s): return
  if kind=='movie':
   x=(await s.execute(select(Movie).where(Movie.code==code))).scalar_one_or_none()
   if not x:return await m.answer('❌ Kino topilmadi.')
   if x.vip_only and not vip(u):return await m.answer('👑 Bu kino faqat VIP uchun.')
   title=x.title_ru if u.language=='ru' else x.title_uz;desc=x.description_ru if u.language=='ru' else x.description_uz
   metadata=getattr(x,'metadata_text',None) or f'🎬 {title}\n📅 {x.year or '-'}\n🎭 {x.genre or '-'}\n🌍 {x.country or '-'}\n⭐ {x.rating or '-'}\n🔢 Kod: {x.code}\n\n📝 {desc}'
   metadata_entities=deserialize_entities(getattr(x,'metadata_entities',None) or [])
   protect=protect_for_user(m.from_user.id, settings.admins)
   if x.poster_file_id:await m.answer_photo(x.poster_file_id,caption=desc or title,protect_content=protect)
   if x.video_file_id:await m.answer_video(x.video_file_id,caption=metadata,caption_entities=metadata_entities or None,protect_content=protect)
  elif kind=='series':
   x=(await s.execute(select(Series).where(Series.code==code))).scalar_one_or_none()
   if not x:return await m.answer('❌ Serial topilmadi.')
   if x.vip_only and not vip(u):return await m.answer('👑 Bu serial faqat VIP uchun.')
   eps=[]
   # Season buttons are generated by series handler after normal code entry; here just show code guidance.
   await m.answer(f'📺 {x.title_ru if u.language=="ru" else x.title_uz}\n\nSerial kodini yuboring: {x.code}')

@router.message(F.text.in_({'📢 Kanalimiz', '📢 Наш канал'}))
async def channel_menu(m):
    async with Session() as s:
        u=(await s.execute(select(User).where(User.telegram_id==m.from_user.id))).scalar_one_or_none()
    lng = u.language if u else 'uz'
    url = settings.ad_channel_url
    if url:
        await m.answer((UZ if lng=='uz' else RU)['ad_channel'], reply_markup=InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text=(UZ if lng=='uz' else RU)['ad_channel'], url=url)]]))
    else:
        await m.answer((UZ if lng=='uz' else RU)['ad_channel'] + '\n\n⚠️ Kanal havolasi hali sozlanmagan.')

@router.message(F.text.in_({'ℹ️ Bot haqida', 'ℹ️ О боте'}))
async def about_menu(m):
    async with Session() as s:
        u=(await s.execute(select(User).where(User.telegram_id==m.from_user.id))).scalar_one_or_none()
    lng = u.language if u else 'uz'
    await m.answer((UZ if lng=='uz' else RU)['about'])

@router.message(F.contact)
async def contact(m,state):
 if not m.contact.user_id or m.contact.user_id!=m.from_user.id:return await m.answer('❌ Faqat o‘z Telegram akkauntingiz raqamini yuboring.')
 async with Session() as s:u=(await s.execute(select(User).where(User.telegram_id==m.from_user.id))).scalar_one();u.registration_status=True;u.last_activity=datetime.now(timezone.utc);await s.commit();lng=u.language
 data=await state.get_data();payload=data.get('start_payload','');await state.clear()
 if not await show(m.bot,m,m.from_user.id):return
 await m.answer((UZ if lng=='uz' else RU)['main'],reply_markup=main(lng=='ru'))
 if payload:await open_payload(m,payload)
