from alembic import op
import sqlalchemy as sa

revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('users',sa.Column('id',sa.Integer,primary_key=True),sa.Column('telegram_id',sa.BigInteger,unique=True,index=True),sa.Column('username',sa.String(255)),sa.Column('first_name',sa.String(255)),sa.Column('language',sa.String(2),nullable=False,server_default='uz'),sa.Column('registration_status',sa.Boolean,server_default=sa.text('false')),sa.Column('vip_expires_at',sa.DateTime(timezone=True)),sa.Column('referred_by',sa.BigInteger),sa.Column('referral_count',sa.Integer,server_default='0'),sa.Column('qualified_referral_count',sa.Integer,server_default='0'),sa.Column('is_blocked',sa.Boolean,server_default=sa.text('false')),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('last_activity',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('movies',sa.Column('id',sa.Integer,primary_key=True),sa.Column('code',sa.String(64),unique=True,index=True),sa.Column('title_uz',sa.Text),sa.Column('title_ru',sa.Text),sa.Column('description_uz',sa.Text),sa.Column('description_ru',sa.Text),sa.Column('description_uz_entities',sa.JSON),sa.Column('description_ru_entities',sa.JSON),sa.Column('year',sa.Integer),sa.Column('genre',sa.String(255)),sa.Column('country',sa.String(255)),sa.Column('rating',sa.String(32)),sa.Column('poster_file_id',sa.String(512)),sa.Column('video_file_id',sa.String(512)),sa.Column('video_file_unique_id',sa.String(512)),sa.Column('source_channel_id',sa.BigInteger),sa.Column('source_message_id',sa.BigInteger),sa.Column('vip_only',sa.Boolean,server_default=sa.text('false')),sa.Column('views',sa.Integer,server_default='0'),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('series',sa.Column('id',sa.Integer,primary_key=True),sa.Column('code',sa.String(64),unique=True,index=True),sa.Column('title_uz',sa.Text),sa.Column('title_ru',sa.Text),sa.Column('description_uz',sa.Text),sa.Column('description_ru',sa.Text),sa.Column('description_uz_entities',sa.JSON),sa.Column('description_ru_entities',sa.JSON),sa.Column('year',sa.Integer),sa.Column('genre',sa.String(255)),sa.Column('country',sa.String(255)),sa.Column('rating',sa.String(32)),sa.Column('poster_file_id',sa.String(512)),sa.Column('vip_only',sa.Boolean,server_default=sa.text('false')),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('episodes',sa.Column('id',sa.Integer,primary_key=True),sa.Column('series_id',sa.Integer,sa.ForeignKey('series.id',ondelete='CASCADE'),index=True),sa.Column('season_number',sa.Integer),sa.Column('episode_number',sa.Integer),sa.Column('title_uz',sa.Text),sa.Column('title_ru',sa.Text),sa.Column('description_uz',sa.Text),sa.Column('description_ru',sa.Text),sa.Column('description_uz_entities',sa.JSON),sa.Column('description_ru_entities',sa.JSON),sa.Column('video_file_id',sa.String(512)),sa.Column('video_file_unique_id',sa.String(512)),sa.Column('source_channel_id',sa.BigInteger),sa.Column('source_message_id',sa.BigInteger),sa.Column('vip_only',sa.Boolean,server_default=sa.text('false')),sa.Column('views',sa.Integer,server_default='0'),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('mandatory_channels',sa.Column('id',sa.Integer,primary_key=True),sa.Column('chat_id',sa.BigInteger,index=True),sa.Column('title',sa.Text),sa.Column('url',sa.Text),sa.Column('chat_type',sa.String(32)),sa.Column('tracking_code',sa.String(64),unique=True),sa.Column('active',sa.Boolean,server_default=sa.text('true')),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('subscription_tracking',sa.Column('id',sa.Integer,primary_key=True),sa.Column('subscription_id',sa.Integer,sa.ForeignKey('mandatory_channels.id',ondelete='CASCADE'),index=True),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id',ondelete='CASCADE'),index=True),sa.Column('tracking_code',sa.String(64)),sa.Column('invite_link',sa.Text),sa.Column('event_type',sa.String(64)),sa.Column('joined_at',sa.DateTime(timezone=True)),sa.Column('checked_at',sa.DateTime(timezone=True)),sa.Column('is_subscribed',sa.Boolean),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.UniqueConstraint('subscription_id','user_id',name='uq_sub_user'))
    op.create_table('vip_plans',sa.Column('id',sa.Integer,primary_key=True),sa.Column('name_uz',sa.String(100)),sa.Column('name_ru',sa.String(100)),sa.Column('days',sa.Integer),sa.Column('price',sa.Integer),sa.Column('active',sa.Boolean,server_default=sa.text('true')))
    op.create_table('vip_payments',sa.Column('id',sa.Integer,primary_key=True),sa.Column('payment_id',sa.String(64),unique=True,index=True),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id')),sa.Column('plan_id',sa.Integer,sa.ForeignKey('vip_plans.id')),sa.Column('amount',sa.Integer),sa.Column('currency',sa.String(8),server_default='UZS'),sa.Column('status',sa.String(16),server_default='PENDING'),sa.Column('receipt_file_id',sa.String(512)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('verified_at',sa.DateTime(timezone=True)),sa.Column('verified_by',sa.BigInteger),sa.Column('rejection_reason',sa.Text))
    op.create_table('vip_transactions',sa.Column('id',sa.Integer,primary_key=True),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id')),sa.Column('type',sa.String(32)),sa.Column('days',sa.Integer),sa.Column('payment_id',sa.String(64)),sa.Column('admin_id',sa.BigInteger),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('referrals',sa.Column('id',sa.Integer,primary_key=True),sa.Column('referrer_id',sa.Integer,sa.ForeignKey('users.id')),sa.Column('referred_user_id',sa.Integer,sa.ForeignKey('users.id'),unique=True),sa.Column('status',sa.String(32),server_default='PENDING'),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('qualified_at',sa.DateTime(timezone=True)))
    op.create_table('referral_rewards',sa.Column('id',sa.Integer,primary_key=True),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id')),sa.Column('required_referrals',sa.Integer),sa.Column('from_referral_number',sa.Integer),sa.Column('to_referral_number',sa.Integer),sa.Column('vip_days',sa.Integer),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.UniqueConstraint('user_id','required_referrals',name='uq_reward'))
    op.create_table('settings',sa.Column('key',sa.String(100),primary_key=True),sa.Column('value',sa.Text))
    op.create_table('broadcasts',sa.Column('id',sa.Integer,primary_key=True),sa.Column('admin_id',sa.BigInteger),sa.Column('kind',sa.String(32)),sa.Column('sent',sa.Integer,server_default='0'),sa.Column('failed',sa.Integer,server_default='0'),sa.Column('blocked',sa.Integer,server_default='0'),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('content_views',sa.Column('id',sa.Integer,primary_key=True),sa.Column('content_type',sa.String(32)),sa.Column('content_id',sa.Integer),sa.Column('user_id',sa.Integer,sa.ForeignKey('users.id')),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    for name,days,price in [('3 kun',3,7000),('7 kun',7,15000),('14 kun',14,23000),('30 kun',30,39000),('90 kun',90,55000),('1 yil',365,145000)]: op.execute(sa.text("INSERT INTO vip_plans (name_uz,name_ru,days,price) VALUES (:n,:n,:d,:p)").bindparams(n=name,d=days,p=price))

def downgrade():
    for t in ['content_views','broadcasts','settings','referral_rewards','referrals','vip_transactions','vip_payments','vip_plans','subscription_tracking','mandatory_channels','episodes','series','movies','users']: op.drop_table(t)
